#!/bin/sh
### BEGIN INIT INFO
# Provides:          lddmodules
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load ldd kernel modules
### END INIT INFO

RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color

case "$1" in
    start)
        printf "${GREEN}Loading scull driver...${NC}\n"
        modprobe scull
        printf "${BLUE}Loading faulty driver...${NC}\n"
        modprobe faulty
        printf "${RED}Loading hello module...${NC}\n"
        modprobe hello
        ;;
    stop)
        printf "${RED}Unloading hello module...${NC}\n"
        rmmod hello
        printf "${BLUE}Unloading faulty driver...${NC}\n"
        rmmod faulty
        printf "${GREEN}Unloading scull driver...${NC}\n"
        rmmod scull
        ;;
    *)
        printf "Usage: $0 {start|stop}\n"
        exit 1
        ;;
esac

exit 0
